package types

const (
	OperatorNamespace           string = "nsx-system-operator"
	ConfigMapName               string = "nsx-ncp-operator-config"
	NetworkCRDName              string = "cluster"
	NsxNamespace                string = "nsx-system"
	NcpConfigMapName            string = "nsx-ncp-config"
	NodeAgentConfigMapName      string = "nsx-node-agent-config"
	ConfigMapDataKey            string = "ncp.ini"
	NcpConfigMapRenderKey       string = "NSXNCPConfig"
	NodeAgentConfigMapRenderKey string = "NSXNodeAgentConfig"
	NcpImageKey                 string = "NcpImage"
	NcpReplicasKey              string = "NcpReplicas"
	NsxNodeAgentDsName          string = "nsx-node-agent"
	NsxNcpBootstrapDsName       string = "nsx-ncp-bootstrap"
	NsxNcpDeploymentName        string = "nsx-ncp"
	NetworkType                 string = "ncp"
	LbCertRenderKey             string = "LbCert"
	LbKeyRenderKey              string = "LbKey"
	NsxCertRenderKey            string = "NsxCert"
	NsxKeyRenderKey             string = "NsxKey"
	NsxCARenderKey              string = "NsxCA"
	NsxSecretName               string = "nsx-secret"
	NsxCertTempPath             string = "/tmp/nsx.cert"
	NsxKeyTempPath              string = "/tmp/nsx.key"
	NsxCATempPath               string = "/tmp/nsx.ca"
)
