# Copyright © 2026 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsx-ncp-operator
  namespace: nsx-system-operator
  labels:
    tier: nsx-networking
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: nsx-ncp-operator
  template:
    metadata:
      labels:
        name: nsx-ncp-operator
        tier: nsx-networking
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: nsx-ncp-operator
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
      - effect: NoSchedule
        key: node.kubernetes.io/network-unavailable
      volumes:
      - name: host-os-release
        configMap:
          name: fake-os-release
          items:
          - key: os-release
            path: os-release
      containers:
        - name: nsx-ncp-operator
          image: vmware/nsx-container-plugin-operator:latest
          command: ["/bin/bash", "-c", "nsx-ncp-operator --metrics-server-bind-address=:8181"]
          volumeMounts:
          - mountPath: /host/etc/os-release
            name: host-os-release
            subPath: os-release
          imagePullPolicy: Never
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nsx-ncp-operator"
            - name: NCP_IMAGE
              value: "vmware/fake-ncp:v1"
            - name: WATCH_NAMESPACE
              value: "nsx-system-operator"
